Turret
primo4586/Turret-learning-project pull request #4
Opened 2023-12-15 12:04 UTC by eilonhuppert

2023-12-15 12:08 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final double minimumMistake = 30;
change to minimum

2023-12-15 12:13 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final double minimumTime = 10;
change to minimum error and no need for minimum time for the turret

2023-12-15 12:13 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +  public static TurretSubsystem instance;
change to private

2023-12-15 12:18 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    }
change to `if (Math.abs(motor.getClosedLoopError().getValue()) < minimumError){`

2023-12-15 12:38 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    }
replace place to pose(also in the name)

2023-12-15 19:31 UTC, eilonhuppert commented on src/main/java/frc/robot/Constants.java
> +    public static final double minimumTime = 10;
V

2023-12-15 19:31 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    }
V

2023-12-15 19:31 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    }
V

2023-12-15 19:32 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +  public static TurretSubsystem instance;
V but it's to small to commit

2023-12-15 19:35 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    }
actually change the function name to `putTurretInPose` and `double place` to `double degree`

2023-12-15 19:38 UTC, ori-coval requested changes

2023-12-15 19:38 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    configs.Feedback.SensorToMechanismRatio = SensorToMechanismRatio;
the position value right now is in encoder ticks(1024 ticks is 1 rotation) change it so it would in degrees

2023-12-15 19:57 UTC, ori-coval requested changes

2023-12-15 19:57 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final double minimumTimeForTurret = 10;
no need for minimumTimeForTurret remove it

fro the turret we don't check if it stayed in the spot because it doesn't do big movements and it is also pretty slow

2023-12-15 19:57 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final double turretTurnSpeed = 0.5; // TODO: give good nums also
change to turretManualSpeed

2023-12-15 19:57 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    public void manualTurnForTurret(int vector){ // vector is 1/-1
change to `manualTurnTurret` and get `double speed` not `int vector` and do `this.motor.set(speed);` if you want to do what you did here do it in a command not as a function

2023-12-15 20:06 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    configs.Feedback.SensorToMechanismRatio = SensorToMechanismRatio;
V

2023-12-15 20:07 UTC, eilonhuppert commented on src/main/java/frc/robot/Constants.java
> +    public static final double minimumTimeForTurret = 10;
V

2023-12-15 20:08 UTC, eilonhuppert commented on src/main/java/frc/robot/Constants.java
> +    public static final double turretTurnSpeed = 0.5; // TODO: give good nums also
V

2023-12-15 20:15 UTC, ori-coval requested changes

2023-12-15 20:15 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    configs.Feedback.SensorToMechanismRatio = SensorToMechanismRatio;
add forward and backword limits so the motor won't get out of the acceptable range

2023-12-16 07:32 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    configs.Feedback.SensorToMechanismRatio = SensorToMechanismRatio;
![image](https://github.com/primo4586/Turret-learning-project/assets/95046996/01b892b4-5e22-472d-a81b-64ad0e6bd6d7)

2023-12-16 08:33 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    public void manualTurnForTurret(int vector){ // vector is 1/-1
V

2023-12-16 08:33 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    configs.Feedback.SensorToMechanismRatio = SensorToMechanismRatio;
V

2023-12-16 08:35 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    }
V

2023-12-16 08:52 UTC, noamgo commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +  private TalonFX motor;
Give a more significant name than "motor", for example, **m_turret**
so it will be clearer which motor it is (in the whole code)

2023-12-16 08:58 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +  private TalonFX motor;
Remember start motors and other objects with m_  for example `"m_motorName"`

2023-12-16 11:26 UTC, ori-coval requested changes

2023-12-16 11:26 UTC, ori-coval commented on src/main/java/frc/robot/commands/MoveTurretToFixdDegree.java
> +  public MoveTurretToFixdDegree(double degree) {
remove the fixd

2023-12-16 11:26 UTC, ori-coval commented on src/main/java/frc/robot/commands/MoveTurretToFixdDegree.java
> +    return false;
you can do it in 1 line

2023-12-16 11:29 UTC, ori-coval requested changes

2023-12-16 11:29 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final double TurretRestartDgree = 0;
reset not restart and typo in degree

2023-12-16 11:29 UTC, ori-coval commented on src/main/java/frc/robot/commands/RestartTurret.java
> +  public RestartTurret() {
reset not restart

2023-12-16 11:29 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    public void manualTurnForTurret(double speed){
change to setSpeed

2023-12-16 19:23 UTC, danielml2 requested changes

2023-12-16 19:23 UTC, danielml2 commented on src/main/java/frc/robot/commands/ResetTurret.java
> +  }
The degree variable is a bit useless here, since you're resetting to a constant degree, you could just set the turret to that position 

(i'm on mobile so i cant mark this as requesting changes yet)

2023-12-17 06:48 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    public void manualTurnForTurret(double speed){
V

2023-12-17 06:48 UTC, eilonhuppert commented on src/main/java/frc/robot/commands/RestartTurret.java
> +  public RestartTurret() {
V

2023-12-17 06:48 UTC, eilonhuppert commented on src/main/java/frc/robot/Constants.java
> +    public static final double TurretRestartDgree = 0;
V

2023-12-17 06:48 UTC, eilonhuppert commented on src/main/java/frc/robot/commands/MoveTurretToFixdDegree.java
> +    return false;
V

2023-12-17 06:48 UTC, eilonhuppert commented on src/main/java/frc/robot/commands/MoveTurretToFixdDegree.java
> +  public MoveTurretToFixdDegree(double degree) {
V

2023-12-17 07:51 UTC, ori-coval requested changes

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/TrackTargetWithTurret.java
> +    turret.putTurretInPose(degree);
replace degree with the vision

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/TrackTargetWithTurret.java
> +    turret.setSpeed(0);
remove this we dont want the turret to stop

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +    return false;
you can write this function in 1 line

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurretSubsystem.java
> +  public void putTurretInPose(double degree) {
change to putTurretAtAngle

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/MoveTurretToDegree.java
> +    turret.setSpeed(0);
dont stop it at the end

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/MoveTurretToDegree.java
use instant command

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/ResetTurret.java
use instant command

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/ResetTurret.java
> +    turret.setSpeed(0);
usless

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/ResetTurret.java
> +    return turret.checkTurretPosition();
usless

2023-12-17 07:51 UTC, ori-coval commented on src/main/java/frc/robot/commands/ManualTurnForTurret.java
> +    this.vector = vector; // vector is 1 or -1 for forward or backword
right or left not forward or backword

2023-12-17 17:45 UTC, ori-coval requested changes

2023-12-17 17:45 UTC, ori-coval commented on src/main/java/frc/robot/commands/ResetTurret.java
> +  private double degree;
remove this veriable

2023-12-17 17:45 UTC, ori-coval commented on src/main/java/frc/robot/commands/ResetTurret.java
> +    turret.putTurretInAngle(degree);
just put the constant here directly no need for the degree veriable

2023-12-17 19:29 UTC, ori-coval approved these changes

2023-12-17 19:35 UTC, merged

2023-12-17 19:39 UTC, eilonhuppert commented
וואו זה קוד מדהים

2023-12-17 19:39 UTC, eilonhuppert commented
איזה קוד מדהים זה