Hoode branch
primo4586/Turret-learning-project pull request #6
Opened 2023-12-15 15:41 UTC by Yair4586

2023-12-15 15:58 UTC, ori-coval requested changes

2023-12-15 15:58 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
put all the constant in a single constants class HoodConstants
change to hood

2023-12-15 15:58 UTC, ori-coval commented on src/main/java/frc/robot/commands/HoodePosReset.java
> +  Timer timer;
no need for timer
change to hood

2023-12-15 15:58 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodeSubsystem.java
change al the names to hood 

use import static `frc.robot.Constants.HoodConstants.*;` and then remove all the other constants import. and there is no need to do `Constants.HoodeConstants.HoodPort` you can just write `HoodPort` and it works and looks better and preform better

2023-12-15 15:58 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodeSubsystem.java
> +      System.out.println("Could not apply config, error code:"+statusCode.toString());
add to what is being printed to indicate the problem was with the hood

2023-12-15 15:58 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodeSubsystem.java
> +  private final MotionMagicVoltage m_PositionVoltage = new MotionMagicVoltage(0);
change the name so it would be clearer that it is using motion magic

2023-12-15 15:58 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodeSubsystem.java
> +  }
change to getHoodPose

also you need to return the current motor pose using motor.getPosition.get()(something like that)

2023-12-15 17:29 UTC, ori-coval requested changes
fix all the problem listed

2023-12-15 17:29 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final int HoodPort = 1;
put all the constant in a single constants class HoodConstants
change to hood

2023-12-15 17:29 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +import frc.robot.Constants.PdConstants;
after moving all the constant in a single constants class HoodConstants

remove `import frc.robot.Constants;
import frc.robot.Constants.PdConstants;`

2023-12-15 17:29 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +      System.out.println("Could not apply config, error code:"+statusCode.toString());
add to what is being printed to indicate the problem was with the hood

2023-12-15 17:29 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  private final MotionMagicVoltage m_PositionVoltage = new MotionMagicVoltage(0);
change the name so it would be clearer that it is using motion magic

2023-12-15 17:29 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    return this.hoodDeg;
you need to return the current motor pose using `motor.getPosition().getValue()`

2023-12-15 18:29 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    // creat the full MotionMagic
create

2023-12-15 19:31 UTC, ori-coval requested changes

2023-12-15 19:31 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +  public static class MaxVolConstants{
add MaxVolConstants to hoodConstants

2023-12-15 19:31 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +import frc.robot.Constants;
after fixing constants remove `import frc.robot.Constants;`

2023-12-15 19:31 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    double targetPosition = degrees * TICKS_PER_DEGREE;
insted of doing this

do it in the `configuration.Feedback.SensorToMechanismRatio = gearRatio;` so 1 unit would be a degree

2023-12-15 19:40 UTC, lonaim commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +import frc.robot.Constants;
did it

2023-12-15 19:40 UTC, lonaim commented on src/main/java/frc/robot/Constants.java
> +  public static class MaxVolConstants{
did it

2023-12-15 19:41 UTC, lonaim commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    double targetPosition = degrees * TICKS_PER_DEGREE;
so I need to change the configuration.Feedback.SensorToMechanismRatio = gearRatio;
to onfiguration.Feedback.SensorToMechanismRatio =  TICKS_PER_DEGREE;
?

2023-12-15 19:59 UTC, ori-coval requested changes

2023-12-15 19:59 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    configuration.Voltage.PeakReverseVoltage = MaxVolConstants.peekRvol;
you need to remove `MaxVolConstants.` because you moved the constants

2023-12-15 19:59 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    double targetPosition = degrees * TICKS_PER_DEGREE;
yep

2023-12-15 20:07 UTC, lonaim commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    double targetPosition = degrees * TICKS_PER_DEGREE;
did it

2023-12-15 20:08 UTC, ori-coval requested changes

2023-12-15 20:08 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  public void moveHoodTo(double targetPosition){
make it degrees again cause its in degrees

2023-12-15 20:18 UTC, ori-coval requested changes

2023-12-15 20:18 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final int HoodPort = 1;
`HoodID`

2023-12-15 20:18 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  public HoodSubsystem() {
change Constractor to private

2023-12-15 20:18 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  public static HoodSubsystem instance;
change to private

2023-12-15 20:18 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    configuration.Feedback.SensorToMechanismRatio = TICKS_PER_DEGREE;
add forward and backword limits so the motor won't get out of the acceptable range

2023-12-15 20:18 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    return Math.abs(getHoodPose() - hoodDeg) <= READY_DEG_TOLERANCE;
you can use `(Math.abs(motor.getClosedLoopError().getValue()) < minimumError)` and then you don't need `hoodDeg` and it is also more accurate

2023-12-15 21:14 UTC, lonaim commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    return Math.abs(getHoodPose() - hoodDeg) <= READY_DEG_TOLERANCE;
did it

2023-12-15 21:14 UTC, lonaim commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  public static HoodSubsystem instance;
did it

2023-12-15 21:14 UTC, lonaim commented on src/main/java/frc/robot/Constants.java
> +    public static final int HoodPort = 1;
did it

2023-12-15 21:37 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    configuration.Feedback.SensorToMechanismRatio = TICKS_PER_DEGREE;
![image](https://github.com/primo4586/Turret-learning-project/assets/95046996/8a1178bf-b9bf-42a0-9cf9-7b14bf816350)
use constant and also do it for backwords

2023-12-15 22:00 UTC, lonaim commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    configuration.Feedback.SensorToMechanismRatio = TICKS_PER_DEGREE;
Ok, on it

2023-12-15 22:44 UTC, lonaim commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    configuration.Feedback.SensorToMechanismRatio = TICKS_PER_DEGREE;
did it😎

2023-12-15 22:59 UTC, ori-coval approved these changes

2023-12-16 08:59 UTC, noamgo commented on src/main/java/frc/robot/Constants.java
> +    public static final double mmj = 50;
Give more significant names (give longer and clearer names).
Like ### mmCruise
and so on.

2023-12-16 09:00 UTC, noamgo commented on src/main/java/frc/robot/Constants.java
> +    public static final double peekFvol = 11.5;
Give more significant names (give longer and clearer names).
Like **peekForwardVoltage**.

2023-12-16 09:07 UTC, noamgo commented on src/main/java/frc/robot/Constants.java
> +    public static final double kp = 24;
We use pd which means you should have `kd` too (In subsystem and in constants)

2023-12-16 10:09 UTC, ori-coval requested changes

2023-12-16 10:09 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
you changed the constants name but didn't change to constants name in the subsystem

when changing variables and constants names use the F2 key or func F2 if you're using a laptop and then it would change the name of the variable everywhere and you wouldn't have to change it manually

2023-12-16 10:23 UTC, ori-coval commented
yair please replay to the tasks you finish that you finished them so we would know that you finished them

2023-12-16 17:41 UTC, lonaim commented
@ori-coval  @noamgo 
We would appreciate it if you go through the subsystem to see if anything needs to be fixed or added
After you confirm, a new PR will be opened for the commands

2023-12-16 18:25 UTC, ori-coval requested changes

2023-12-16 18:25 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    m_hood.setControl(motionMagic.withPosition(0));
you need to set the motor pose to zero not to tell it to got to zero

2023-12-16 18:27 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +    m_hood.setControl(motionMagic.withPosition(0));
use `motor.setPosition(0);`

2023-12-16 18:54 UTC, ori-coval requested changes

2023-12-16 18:54 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  private double hoodDeg;//the degrees the hood needs to be
delete hoodDeg

2023-12-16 18:54 UTC, noamgo requested changes

2023-12-16 18:54 UTC, noamgo commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  private double hoodDeg;//the degrees the hood needs to be
Delete this useless thing.

2023-12-16 18:57 UTC, noamgo requested changes

2023-12-16 18:57 UTC, noamgo commented on src/main/java/frc/robot/subsystems/HoodSubsystem.java
> +  private TalonFX m_hood;
Change motor name to `m_hoodMotor`.

2023-12-16 19:13 UTC, ori-coval approved these changes

2023-12-16 19:16 UTC, noamgo approved these changes

2023-12-16 19:18 UTC, merged