CreatedShootBase
primo4586/Turret-learning-project pull request #7
Opened 2023-12-15 16:13 UTC by DrorMargalit17

2023-12-15 17:40 UTC, ori-coval requested changes

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +
you are not applying the config to the motor

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +    configs.Feedback.SensorToMechanismRatio = 50;
constants

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +  public static class TurrentShotConstants{
change to ShooterConstants

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +public class TurrentShot extends SubsystemBase {
change class name to `ShooterSubsystem`

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final int KshotMotorID = 20;
`KShooterMotorID`

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final int KenterBallMotorID = 20;
`KFeederMotorID`

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
change it to shooter everywhere

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +  private TalonFX shotMotor;
`shooterMotor`

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +  private TalonFX enterBallMotor;
`shooterMotor`
`feederMotor`

2023-12-15 17:40 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +  private final PositionVoltage m_voltagePosition = new PositionVoltage(0);
no need for that delete it

2023-12-15 22:57 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +  private TalonFX enterBallMotor;
m_shooterMotor

2023-12-16 17:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +  private final PositionVoltage m_voltagePosition = new PositionVoltage(0);
תיקנתי

2023-12-16 17:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +  private TalonFX enterBallMotor;
תיקנתי

2023-12-16 17:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +  private TalonFX shotMotor;
תיקנתי

2023-12-16 17:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/Constants.java
תיקנתי

2023-12-16 17:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/Constants.java
> +    public static final int KenterBallMotorID = 20;
תיקנתי

2023-12-16 17:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/Constants.java
> +    public static final int KshotMotorID = 20;
תיקנתי

2023-12-16 17:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +public class TurrentShot extends SubsystemBase {
תיקנתי

2023-12-16 17:04 UTC, DrorMargalit17 commented on src/main/java/frc/robot/Constants.java
> +  public static class TurrentShotConstants{
תיקנתי

2023-12-16 17:04 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +    configs.Feedback.SensorToMechanismRatio = 50;
תיקנתי

2023-12-16 17:04 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/TurrentShot.java
> +
תיקנתי

2023-12-16 17:45 UTC, ori-coval requested changes

2023-12-16 17:45 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +import frc.robot.Constants.ShooterConstants;
import it as `import static frc.robot.Constants.ShooterConstants.*;`

and the remove the `ShooterConstants.` in the rest of the subsystem

2023-12-16 17:45 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +    configs.Feedback.SensorToMechanismRatio = ShooterConstants.SensorToMechanismRatio;
you have already done this it at line 52 delete it from here

2023-12-16 17:45 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  }
put the singleton stuff at the start of the class

2023-12-16 17:58 UTC, noamgo requested changes

2023-12-16 17:58 UTC, noamgo commented on src/main/java/frc/robot/Constants.java
> +    public static final double ShooterSpeed = 12700; // 13500
Add lines of space between each category so it will be easier to read.

2023-12-16 18:03 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  }
done.

2023-12-16 18:04 UTC, DrorMargalit17 commented on src/main/java/frc/robot/Constants.java
> +    public static final double ShooterSpeed = 12700; // 13500
irit hasportait

2023-12-16 18:06 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +    configs.Feedback.SensorToMechanismRatio = ShooterConstants.SensorToMechanismRatio;
done.

2023-12-16 18:12 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +import frc.robot.Constants.ShooterConstants;
done.

2023-12-16 18:56 UTC, danielml2 commented
the commit messages are great and all generally, but at least please include a space between words in them

2023-12-16 19:03 UTC, ori-coval commented
> the commit messages are great and all generally, but at least please include a space between words in them

2023-12-16 19:03 UTC, noamgo commented
> the commit messages are great and all generally, but at least please include a space between words in them

For Real :>

2023-12-16 19:04 UTC, noamgo approved these changes

2023-12-16 19:26 UTC, danielml2 requested changes

2023-12-16 19:26 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  public boolean ChecksIfSpeedRight() {
Use lowerCamelCase formatting for methods (instead of ChecksIfSpeedRight, do checksIfSpeedRight)

2023-12-16 19:52 UTC, ori-coval approved these changes

2023-12-16 19:58 UTC, ori-coval requested changes

2023-12-16 19:58 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  //להפעיל את המנוע Shooter
wtf is this language[🤮](https://emojipedia.org/face-vomiting)[🤮](https://emojipedia.org/face-vomiting)

2023-12-16 19:58 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  //להפעיל את המנוע Feeder
Comment
wtf is this language[🤮](https://emojipedia.org/face-vomiting)[🤮](https://emojipedia.org/face-vomiting)

2023-12-16 20:04 UTC, ori-coval approved these changes

2023-12-16 20:04 UTC, merged